faceLogin/faceLogin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include(('faceVerify.urls','faceVerify'), namespace='faceVerify')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, 
document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, 
document_root=settings.MEDIA_ROOT)

faceLogin/faceVerify/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.homepage, name='home'),
    path('login/', views.login_request, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_request, name='logout'),
    path('profile/', views.profile_request, name='profile'),
]

faceLogin/faceVerify/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Profile(models.Model): 
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=250)
    picture = models.ImageField(upload_to='images/')

@receiver(post_save, sender=User)
def create_profile(sender ,instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

faceLogin/faceVerify/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Profile

class NewUserForm(UserCreationForm):
    email = forms.EmailField()
    picture = forms.ImageField()
    description = forms.CharField(max_length=250)
    class Meta():
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        if not commit:
            raise NotImplementedError("Can't create User and UserProfile without database save")
        user = super(NewUserForm, self).save(commit=True)
        user.email = self.cleaned_data.get('email')
        user.save()
        return user

class NewAuthenticationForm(AuthenticationForm):    
    image = forms.CharField(widget=forms.HiddenInput())

faceLogin/faceVerify/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from .forms import NewUserForm, NewAuthenticationForm
from django.contrib.auth import  login,logout
from .backends import FaceAuthBackend
import base64

def homepage(request) :
    return render(request=request, template_name="main/home.html")

def register(request):
    if request.method=='POST':
        form = NewUserForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.profile.description = form.cleaned_data.get('description')
            user.profile.picture = form.cleaned_data.get('picture')
            user.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"New Account Created: {username}")
            login(request, user,backend='faceVerify.backends.FaceAuthBackend')
            messages.info(request, f"You are logged in as {username}")
            return render(request, "main/profile.html", context={'profile': user.profile})
        else:
            print(form.errors)
            for msg in form.error_messages:
                messages.error(request, f"{msg}: {form.error_messages[msg]}")
                print(form.error_messages[msg])
    
    form = NewUserForm()
    return render(request, "main/register.html", context = {'form': form})

def logout_request(request) :
    logout(request)
    messages.info(request, 'Logged out successfully')
    return redirect("faceVerify:home")

def login_request(request) :
    if request.method == 'POST':
        form = NewAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            image = form.cleaned_data.get('image')
            print(type(image))
            f = FaceAuthBackend()
            user = f.authenticate(request, username, password)
            if user is not None:
                login(request,user,backend='faceVerify.backends.FaceAuthBackend')
                messages.info(request, f"You are logged in as {username}")
                return render(request, "main/profile.html", context={'profile': user.profile})
            else :
                messages.error(request, "Authentication Failed")
        else:
            print(form.errors)
            for msg in form.error_messages:
                messages.error(request, f"{form.error_messages[msg]}")
    form = NewAuthenticationForm()
    return render(request,"main/login.html", context={'form':form})


def profile_request(request) :
    return render(request=request, template_name="main/profile.html",context={'profile':request.user.profile})

faceLogin/faceVerify/templates/main/caption-generator.html
{% extends "main/header.html" %}
{% block content%}
<div class="container center-align">
    <form method="POST" enctype="multipart/form-data" class="card  accent-5 hoverable"> 
        {% csrf_token %}
        <div class="card-panel">
            {{form.as_p}}
            <input type="submit" class="btn caret">
        </div>
    </form>
    <div class='card z-depth-4'>
        {% if caption != None %}
            <img src="{{image.url}}" class='responsive-img materialboxed ' alt="img">
            <p class="materialize-textarea card-content">{{caption}}</p>
        {% endif %}
    </div>
</div>
{% endblock %}

faceLogin/faceVerify/templates/main/header.html
<head>
    {% load static %}
    <link href="{% static 'main/css/materialize.css' %}", rel="stylesheet" > 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script type="text/javascript" src="{% static 'main/js/webcam.min.js' %}"></script>
</head>


<body>
    {% include 'main/includes/navbar.html' %}
    {% include 'main/includes/messages.html' %}
    <br> 
    <div class="container" >
        {% block content %}
        {% endblock %} 
    </div>
</body>

<script>M.AutoInit();</script>

faceLogin/faceVerify/templates/main/home.html
{% extends 'main/header.html' %}

{% block content %}

<div>
    <h1>
        Face Verification Login System
    </h1>
    <a href = '/login/' class="waves-effect waves-light btn-small">Login</a>
    <a href = '/register/' class="waves-effect waves-light btn-small">Register</a>

</div>

{% endblock %}

faceLogin/faceVerify/templates/main/includes/messages.html
{% if messages %}
      {% for message in messages %}
        {% if message.tags == 'success' %}
          <script>M.toast({html:'{{message}}', classes : "green rounded", displayLength:2000});</script>
        {% elif message.tags == 'info' %}              
          <script>M.toast({html:'{{message}}', classes : "blue rounded", displayLength:2000});</script>
        {% elif message.tags == 'warning' %}
          <script>M.toast({html:'{{message}}', classes : "orange rounded", displayLength:10000});</script>
        {% elif message.tags == 'error' %}
          <script>M.toast({html:'{{message}}', classes : "red rounded", displayLength:10000});</script>
        {% endif %}
      {% endfor %}
{% endif %}

faceLogin/faceVerify/templates/main/includes/navbar.html
<nav>
    <div class="nav-wrapper blue-grey darken-2">
        <a href="/" class="brand-logo" style="padding-left: 0.5%;"> FaceLogin </a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="/">Home</a></li>
        {% if user.is_authenticated %}
            <li><a href="/profile">{{user.username}}</a></li>
            <li><a href="/logout">Logout</a></li>
        {% else %}
            <li><a href="/register">Register</a></li>
            <li><a href="/login">Login</a></li>
        {% endif %}
        </ul>
    </div>
</nav>

faceLogin/faceVerify/templates/main/login.html
{% extends "main/header.html" %}
{% block content%}
<form method="POST" enctype='multipart/form-data' id='loginForm'>
    {% csrf_token %}
    {{form}}
    <input type="hidden" name="next" value="{{ next }}">
</form> 
<button id="video-button">Next</button>
<video id="screenshot-video" autoplay></video>
<button id="login-button" >Login</button>
<script>
    const constraints = {
        video: {width: {min: 1280}, height: {min: 720}}
    };

    const captureVideoButton =
    document.querySelector('#video-button');
    const loginButton = document.querySelector('#login-button');
    const video = document.querySelector('#screenshot-video');
    const image_hidden = document.querySelector('#id_image');

    captureVideoButton.onclick = function() {
        captureVideoButton.setAttribute('style','display: none;');
        loginButton.removeAttribute("style");
        navigator.mediaDevices.getUserMedia(constraints).
        then(handleSuccess).catch(handleError);
    };

    loginButton.onclick = video.onclick = function() {
        var canvas = document.createElement("canvas");
        canvas.getContext('2d').drawImage(video, 0, 0, canvas.width, canvas.height);
        image_hidden.value = canvas.toDataURL();
        document.forms["loginForm"].submit();
    };

    function handleSuccess(stream) {
        loginButton.disabled = false;
        video.srcObject = stream;
    }
</script>


 If you don't already have an account, <a href="/register"><strong>Register</strong></a> instead.
{% endblock %}

faceLogin/faceVerify/templates/main/profile.html
{% extends 'main/header.html' %}

{% block content %}
<div class="container">
    <h2 class="accent-1 center-align">{{profile.user.username}}</h2>
    <div class='blue'>
        {{profile.description}}
    </div>
    {{profile.picture}}
    <img src={{profile.picture.url}}>
</div>
{% endblock %}  

faceLogin/faceVerify/templates/main/register.html
{% extends "main/header.html" %}
{% block content%}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}

    <button class='btn-large teal' type="submit">register</button>

</form>

 If you already have an account, <a href="/login"><strong>login</strong></a> instead.

{% endblock %}